# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='username',
        ),
    ]
