# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180725_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='exp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
