# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20180726_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='p1_health',
        ),
        migrations.RemoveField(
            model_name='game',
            name='p1_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='p2_health',
        ),
        migrations.RemoveField(
            model_name='game',
            name='p2_name',
        ),
        migrations.AddField(
            model_name='player',
            name='created',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='login.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='joined',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='login.Game'),
            preserve_default=False,
        ),
    ]
