# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180726_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='p1_brn',
            new_name='creator_brn',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='p1_frz',
            new_name='creator_frz',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='p1_pos',
            new_name='creator_pos',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='p2_brn',
            new_name='member_brn',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='p2_frz',
            new_name='member_frz',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='p2_pos',
            new_name='member_pos',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='created',
            new_name='create',
        ),
        migrations.RemoveField(
            model_name='player',
            name='joined',
        ),
        migrations.AddField(
            model_name='player',
            name='join',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='joiner', to='login.Game'),
            preserve_default=False,
        ),
    ]
