# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180726_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator_health',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='member_health',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
