# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20180726_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creator_turn',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
